controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
index:
    path: /
    controller: App\Controller\IndexController::index
# login_proyecto:
#     path: /login-Proyecto.html
#     controller: App\Controller\RegistroLoginController::index
